name = "NMEAProtocol"
uuid = "ef943452-3a45-4f3f-88dc-bab9b18141fe"
authors = ["nick <nick@shindler.tech> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
